services:
  # The Lua Proxy
  lua-proxy:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      - DB_HOST=192.168.0.111
      - DB_NAME=llm
      - DB_USER=postgres
      - DB_PASS=password
      - OLLAMA_URL=http://192.168.0.111:11434/api/generate

volumes:
  ollama_data:
